# **Esercizi Numpy**

In [1]:
import numpy as np

## **Esercizio 1**
Crea un array NumPy utilizzando arange e verifica il tipo di dato (dtype) e la forma (shape) dell'array.

1. Utilizza la funzione `np.arange()` per creare un array di numeri interi da 10 a 49.

In [2]:
array = np.arange(10,50)
print("L'array costruito è",array)

L'array costruito è [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Verifica il tipo di dato dell'array e stampa il risultato.

In [3]:
tipo=array.dtype
print("Il tipo di dati contenuti nell'array è",tipo)

Il tipo di dati contenuti nell'array è int32


3. Cambia il tipo di dato dell'array in float64 e verifica di nuovo il tipo di dato.

In [4]:
array = np.array(array, dtype='float64')
print("Il tipo di dati contenuti nell'array è",array.dtype)

Il tipo di dati contenuti nell'array è float64


4. Stampa la forma dell'array.

In [5]:
print("Le dimensioni dell'array sono",array.shape)

Le dimensioni dell'array sono (40,)


## **Esercizio 2**

1. Crea un array NumPy 1D di 20 numeri interi casuali compresi tra 10 e 50.

In [6]:
array = np.random.randint(10, 50, 20)
print(array)

[34 28 33 39 37 33 32 37 32 20 32 33 41 11 14 36 18 16 27 31]


2. Utilizza lo slicing per estrarre i primi 10 elementi dell'array.

In [7]:
array2=array[:10]
print(array2)

[34 28 33 39 37 33 32 37 32 20]


3. Utilizza lo slicing per estrarre gli ultimi 5 elementi dell'array.

In [8]:
array3=array[-5:]
print(array3)

[36 18 16 27 31]


4. Utilizza lo slicing per estrarre gli elementi dall'indice 5 all'indice 15 (escluso).

In [9]:
array4=array[5:15]
print(array4)

[33 32 37 32 20 32 33 41 11 14]


5. Utilizza lo slicing per estrarre ogni terzo elemento dell'array.

In [10]:
array5=array[::3]
print(array5)

[34 39 32 20 41 36 27]


6. Modifica, tramite slicing, gli elementi dall'indice 5 all'indice 10 (escluso) assegnando loro il valore 99.

In [11]:
array6=np.copy(array)
array6[5:10]=99*np.ones(5)
print(array6)
print(array)

[34 28 33 39 37 99 99 99 99 99 32 33 41 11 14 36 18 16 27 31]
[34 28 33 39 37 33 32 37 32 20 32 33 41 11 14 36 18 16 27 31]


In [12]:
array6=[1,2,3]
array=array6
array.append(9)
print(array6,array)

[1, 2, 3, 9] [1, 2, 3, 9]


7. Stampa l'array originale e tutti i sottoarray ottenuti tramite slicing.

In [13]:
print("1.",array,"\n2.",array2,"\n3.",array3,"\n4.",array4,"\n5.",array5,"\n6.",array6)

1. [1, 2, 3, 9] 
2. [34 28 33 39 37 33 32 37 32 20] 
3. [36 18 16 27 31] 
4. [33 32 37 32 20 32 33 41 11 14] 
5. [34 39 32 20 41 36 27] 
6. [1, 2, 3, 9]


## **Esercizio 3**

Crea un array utilizzando linspace, cambia la sua forma con reshape, genera un array casuale e calcola la somma degli elementi.

1. Crea un array di 12 numeri equidistanti tra 0 e 1 usando linspace.

In [14]:
array=np.linspace(0,1,12)

2. Cambia la forma dell'array a una matrice 3x4.

In [15]:
reshaped_array=array.reshape((3,4))

3. Genera una matrice 3x4 di numeri casuali tra 0 e 1.

In [16]:
random_array=np.random.rand(3,4)

4. Calcola e stampa la somma degli elementi di entrambe le matrici.

In [17]:
somma1 = np.sum(reshaped_array)
somma2 = np.sum(random_array)
print("La somma degli elementi di\n",reshaped_array,"è", somma1,"\nLa somma degli elementi di\n",random_array,"è",somma2)

La somma degli elementi di
 [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]] è 6.0 
La somma degli elementi di
 [[0.08852303 0.68322189 0.65030193 0.12165191]
 [0.76828009 0.62082733 0.18554508 0.56369881]
 [0.00245544 0.91414399 0.77797434 0.46717432]] è 5.843798143577007
