# **Esercizi Numpy**

In [1]:
import numpy as np

## **Esercizio 1**
Crea un array NumPy utilizzando arange e verifica il tipo di dato (dtype) e la forma (shape) dell'array.

1. Utilizza la funzione `np.arange()` per creare un array di numeri interi da 10 a 49.

In [2]:
array = np.arange(10,50)
print("L'array costruito è",array)

L'array costruito è [10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25 26 27 28 29 30 31 32 33
 34 35 36 37 38 39 40 41 42 43 44 45 46 47 48 49]


2. Verifica il tipo di dato dell'array e stampa il risultato.

In [3]:
tipo=array.dtype
print("Il tipo di dati contenuti nell'array è",tipo)

Il tipo di dati contenuti nell'array è int32


3. Cambia il tipo di dato dell'array in float64 e verifica di nuovo il tipo di dato.

In [4]:
array = np.array(array, dtype='float64')
print("Il tipo di dati contenuti nell'array è",array.dtype)

Il tipo di dati contenuti nell'array è float64


4. Stampa la forma dell'array.

In [5]:
print("Le dimensioni dell'array sono",array.shape)

Le dimensioni dell'array sono (40,)


## **Esercizio 2**

1. Crea un array NumPy 1D di 20 numeri interi casuali compresi tra 10 e 50.

In [6]:
array = np.random.randint(10, 50, 20)
print(array)

[34 28 33 39 37 33 32 37 32 20 32 33 41 11 14 36 18 16 27 31]


2. Utilizza lo slicing per estrarre i primi 10 elementi dell'array.

In [7]:
array2=array[:10]
print(array2)

[34 28 33 39 37 33 32 37 32 20]


3. Utilizza lo slicing per estrarre gli ultimi 5 elementi dell'array.

In [8]:
array3=array[-5:]
print(array3)

[36 18 16 27 31]


4. Utilizza lo slicing per estrarre gli elementi dall'indice 5 all'indice 15 (escluso).

In [9]:
array4=array[5:15]
print(array4)

[33 32 37 32 20 32 33 41 11 14]


5. Utilizza lo slicing per estrarre ogni terzo elemento dell'array.

In [10]:
array5=array[::3]
print(array5)

[34 39 32 20 41 36 27]


6. Modifica, tramite slicing, gli elementi dall'indice 5 all'indice 10 (escluso) assegnando loro il valore 99.

In [11]:
array6=np.copy(array)
array6[5:10]=99*np.ones(5)
print(array6)
print(array)

[34 28 33 39 37 99 99 99 99 99 32 33 41 11 14 36 18 16 27 31]
[34 28 33 39 37 33 32 37 32 20 32 33 41 11 14 36 18 16 27 31]


In [12]:
array6=[1,2,3]
array=array6
array.append(9)
print(array6,array)

[1, 2, 3, 9] [1, 2, 3, 9]


7. Stampa l'array originale e tutti i sottoarray ottenuti tramite slicing.

In [13]:
print("1.",array,"\n2.",array2,"\n3.",array3,"\n4.",array4,"\n5.",array5,"\n6.",array6)

1. [1, 2, 3, 9] 
2. [34 28 33 39 37 33 32 37 32 20] 
3. [36 18 16 27 31] 
4. [33 32 37 32 20 32 33 41 11 14] 
5. [34 39 32 20 41 36 27] 
6. [1, 2, 3, 9]


## **Esercizio 3**

Crea un array utilizzando linspace, cambia la sua forma con reshape, genera un array casuale e calcola la somma degli elementi.

1. Crea un array di 12 numeri equidistanti tra 0 e 1 usando linspace.

In [14]:
array=np.linspace(0,1,12)

2. Cambia la forma dell'array a una matrice 3x4.

In [15]:
reshaped_array=array.reshape((3,4))

3. Genera una matrice 3x4 di numeri casuali tra 0 e 1.

In [16]:
random_array=np.random.rand(3,4)

4. Calcola e stampa la somma degli elementi di entrambe le matrici.

In [17]:
somma1 = np.sum(reshaped_array)
somma2 = np.sum(random_array)
print("La somma degli elementi di\n",reshaped_array,"è", somma1,"\nLa somma degli elementi di\n",random_array,"è",somma2)

La somma degli elementi di
 [[0.         0.09090909 0.18181818 0.27272727]
 [0.36363636 0.45454545 0.54545455 0.63636364]
 [0.72727273 0.81818182 0.90909091 1.        ]] è 6.0 
La somma degli elementi di
 [[0.08852303 0.68322189 0.65030193 0.12165191]
 [0.76828009 0.62082733 0.18554508 0.56369881]
 [0.00245544 0.91414399 0.77797434 0.46717432]] è 5.843798143577007


## **Esercizio 4**

1. Utilizza `np.linspace()` per creare un array di 50 numeri equidistanziati tra 0 e 10.

In [42]:
array1=np.linspace(0,10,50)
array1

array([ 0.        ,  0.20408163,  0.40816327,  0.6122449 ,  0.81632653,
        1.02040816,  1.2244898 ,  1.42857143,  1.63265306,  1.83673469,
        2.04081633,  2.24489796,  2.44897959,  2.65306122,  2.85714286,
        3.06122449,  3.26530612,  3.46938776,  3.67346939,  3.87755102,
        4.08163265,  4.28571429,  4.48979592,  4.69387755,  4.89795918,
        5.10204082,  5.30612245,  5.51020408,  5.71428571,  5.91836735,
        6.12244898,  6.32653061,  6.53061224,  6.73469388,  6.93877551,
        7.14285714,  7.34693878,  7.55102041,  7.75510204,  7.95918367,
        8.16326531,  8.36734694,  8.57142857,  8.7755102 ,  8.97959184,
        9.18367347,  9.3877551 ,  9.59183673,  9.79591837, 10.        ])

2. Utilizza `np.random.rand()` per creare un array di 50 numeri casuali compresi tra 0 e 1.

In [43]:
array2=np.random.rand(50)
array2

array([0.42566508, 0.15042866, 0.91289409, 0.5577497 , 0.69846712,
       0.58462022, 0.56157005, 0.813865  , 0.64534771, 0.82075309,
       0.99094657, 0.91876616, 0.3000175 , 0.42500284, 0.29148032,
       0.61422214, 0.05845464, 0.89931581, 0.43193361, 0.86126079,
       0.85502574, 0.45597135, 0.08458006, 0.12329584, 0.48644105,
       0.04576132, 0.98946141, 0.96307075, 0.93270209, 0.39285367,
       0.16314394, 0.48194728, 0.35039588, 0.44491843, 0.3346531 ,
       0.01442734, 0.92300777, 0.62053264, 0.35816418, 0.31297369,
       0.7639566 , 0.80467988, 0.77938513, 0.37593992, 0.75131423,
       0.72398768, 0.07193669, 0.15747757, 0.79635076, 0.94715468])

3. Somma i due array elemento per elemento per ottenere un nuovo array.

In [44]:
array=array1+array2
array

array([ 0.42566508,  0.3545103 ,  1.32105736,  1.1699946 ,  1.51479365,
        1.60502838,  1.78605984,  2.24243643,  2.27800077,  2.65748778,
        3.0317629 ,  3.16366412,  2.74899709,  3.07806406,  3.14862318,
        3.67544663,  3.32376077,  4.36870356,  4.105403  ,  4.73881181,
        4.93665839,  4.74168563,  4.57437598,  4.81717339,  5.38440023,
        5.14780214,  6.29558386,  6.47327483,  6.6469878 ,  6.31122102,
        6.28559292,  6.80847789,  6.88100813,  7.1796123 ,  7.27342861,
        7.15728449,  8.26994655,  8.17155305,  8.11326622,  8.27215737,
        8.92722191,  9.17202682,  9.3508137 ,  9.15145012,  9.73090607,
        9.90766115,  9.4596918 ,  9.74931431, 10.59226913, 10.94715468])

4. Calcola la somma totale degli elementi del nuovo array

In [45]:
somma=array.sum()
somma

277.4682717891247

5. Calcola la somma degli elementi del nuovo array che sono maggiori di 5.

In [51]:
array3=array.copy()
somma_5=array3[array3>5].sum()
array3[array3>5]

array([ 5.38440023,  5.14780214,  6.29558386,  6.47327483,  6.6469878 ,
        6.31122102,  6.28559292,  6.80847789,  6.88100813,  7.1796123 ,
        7.27342861,  7.15728449,  8.26994655,  8.17155305,  8.11326622,
        8.27215737,  8.92722191,  9.17202682,  9.3508137 ,  9.15145012,
        9.73090607,  9.90766115,  9.4596918 ,  9.74931431, 10.59226913,
       10.94715468])

6. Stampa gli array originali, il nuovo array risultante della somma e le somme calcolate.

In [49]:
print("Array 1:\n",array1,"\nArray 2:\n",array2,"\nSomma:\n",array,"\nSomma degli elementi:",somma,"\nSOmma degli elementi maggiori di 5:",somma_5)

Array 1:
 [ 0.          0.20408163  0.40816327  0.6122449   0.81632653  1.02040816
  1.2244898   1.42857143  1.63265306  1.83673469  2.04081633  2.24489796
  2.44897959  2.65306122  2.85714286  3.06122449  3.26530612  3.46938776
  3.67346939  3.87755102  4.08163265  4.28571429  4.48979592  4.69387755
  4.89795918  5.10204082  5.30612245  5.51020408  5.71428571  5.91836735
  6.12244898  6.32653061  6.53061224  6.73469388  6.93877551  7.14285714
  7.34693878  7.55102041  7.75510204  7.95918367  8.16326531  8.36734694
  8.57142857  8.7755102   8.97959184  9.18367347  9.3877551   9.59183673
  9.79591837 10.        ] 
Array 2:
 [0.42566508 0.15042866 0.91289409 0.5577497  0.69846712 0.58462022
 0.56157005 0.813865   0.64534771 0.82075309 0.99094657 0.91876616
 0.3000175  0.42500284 0.29148032 0.61422214 0.05845464 0.89931581
 0.43193361 0.86126079 0.85502574 0.45597135 0.08458006 0.12329584
 0.48644105 0.04576132 0.98946141 0.96307075 0.93270209 0.39285367
 0.16314394 0.48194728 0.35039588 

## **Esercizio 5**

Scrivere un Sistema che utilizza NumPy per gestire una matrice 2D. Il programma deve presentare un menu interattivo che consente all'utente di
eseguire varie operazioni sulla matrice. 

1. Creare una nuova matrice 2D di dimensioni specificate con numeri casuali.
2. Estrarre e stampare la sotto-matrice centrale.
3. Trasporre la matrice e stamparla.
4. Calcolare e stampare la somma di tutti gli elementi della matrice.
5. Uscire dal programma.

In [53]:
def crea_matrice(n,m):
    matrice = np.random.uniform(0, 10, size=(n, m))
    return matrice

In [62]:
def sottomatrice_centrale(matrice, r, c):
    
    n,m=np.shape(matrice)
    sottomatrice=matrice[1:n-1,1:m-1]
    return sottomatrice

In [59]:
def trasposta(matrice):
    print("La matrice trasposta è",matrice.T)
    return matrice.T

In [73]:
X=True
while X==True:
    opt = int(input("Cosa vuoi fare? \n1.Crea matrice \n2.Sottomatrice centrale \n3.Trasposta \n4.Somma degli elementi \n5.Esci \nScegli opzione: "))
    if opt==1:
        n=int(input("Inserisci numero di righe: "))
        m=int(input("Inserisci numero di colonne: "))
        matrice=crea_matrice(n,m)
    elif opt==2:
        sottomatrice=sottomatrice_centrale(matrice)
    elif opt==3:
        mattrasposta=trasposta(matrice)
    elif opt==4:
        somma = np.sum(matrice)
        print("La somma degli elementi è",somma)
    elif opt==5:
        X=False